USE ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA DATA_ENG_DBT.STAGING TO ROLE DBT_EXECUTOR_ROLE;
GRANT CREATE TABLE ON SCHEMA DATA_ENG_DBT.STAGING TO ROLE DBT_EXECUTOR_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_ENG_DBT.STAGING TO ROLE DBT_EXECUTOR_ROLE;
GRANT INSERT ON ALL TABLES IN SCHEMA DATA_ENG_DBT.STAGING TO ROLE DBT_EXECUTOR_ROLE;
GRANT DELETE ON TABLE DATA_ENG_DBT.STAGING.ASSET_SOURCE TO ROLE DBT_EXECUTOR_ROLE;
GRANT update ON TABLE DATA_ENG_DBT.STAGING.PREDICTION_SOURCE TO ROLE DBT_EXECUTOR_ROLE;
GRANT INSERT ON TABLE DATA_ENG_DBT.STAGING.PREDICTION_SOURCE TO ROLE DBT_EXECUTOR_ROLE;
GRANT INSERT ON TABLE DATA_ENG_DBT.STAGING.POSITION_SOURCE TO ROLE DBT_EXECUTOR_ROLE;
GRANT INSERT ON TABLE DATA_ENG_DBT.STAGING.ACCOUNT_BAL_SOURCE TO ROLE DBT_EXECUTOR_ROLE;



SELECT * FROM DATA_ENG_DBT.STAGING.ASSET_SOURCE
ORDER BY DATE, SYMBOL
;


SELECT * FROM DATA_ENG_DBT.STAGING.PREDICTION_SOURCE
;