
name: Deploy FastAPI to ECS

on:
 push:
  paths:
   - '/src/inference_server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      
      - name: Docker setup
        uses: docker/setup-buildx-action@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t modelapi ./modelapi
          docker tag modelapi:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/docker_containers:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/docker_containers:latest


      - name: Update ECS task definition
        id: update-task
        run: |
          # Fetch the current task definition
          TASK_DEFINITION=$(aws ecs describe-task-definition \
            --task-definition run_inference_server \
            --query "taskDefinition" --output json)

          # Replace the image URI in the task definition JSON
          NEW_TASK_DEF=$(echo "$TASK_DEFINITION" | jq --arg IMAGE_URI "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/docker_containers:latest" \
            '{family: .family, taskRoleArn: .taskRoleArn, executionRoleArn: .executionRoleArn, networkMode: .networkMode, 
              requiresCompatibilities: ["FARGATE"], 
              cpu: "512", memory: "1024",
              containerDefinitions: (.containerDefinitions | map(.image = $IMAGE_URI))}')

          # Register a new task definition with the updated image
          echo "$NEW_TASK_DEF" > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json
      

      - name: Update ECS service with new task definition
        run: |
          # Get the latest revision of the task definition
          TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition run_inference_server --query "taskDefinition.taskDefinitionArn" --output text)
          
          # Update the ECS service to use the new task definition
          aws ecs update-service --cluster modelCluster --service inference-server --task-definition $TASK_DEF_ARN --force-new-deployment
