name: Upload Airflow Dags to S3

on:
  push:
    branches:
      - main
    paths:
    - 'airflow/**'

jobs:
  Push_Dags_to_S3:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
        
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Upload to S3
        run: |
          aws s3 sync ./airflow/dags s3://airflowbucket421654/dags --delete